CREATE TABLE IF NOT EXISTS users (
  `id` BLOB NOT NULL PRIMARY KEY,
  `name` TEXT,
  `email` TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS workspaces (
  `id` BLOB PRIMARY KEY NOT NULL,
  `name` TEXT,
  `data` JSON
);